- name: Include variable files
  include_vars:
    dir: ../../../global_vars
  tags:
    - always

- name: Include user related tasks
  include_tasks: user.yml
  tags:
    - basic_conf
    - basic_conf_user

- name: Include other tasks
  include_tasks: other.yml
  tags:
    - basic_conf
    - basic_conf_other