- name: Remove the Debian DVD from the repository list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: ^deb cdrom
    state: absent
  tags:
    - basic_conf
    - basic_conf_other

- name: Ensure dpkg is ready
  shell: dpkg --configure -a
  tags:
    - basic_conf
    - basic_conf_other

- name: Install useful packages
  apt:
    update_cache: true
    name: "{{ mandatory_packages + non_mandatory_packages }}"
  tags:
    - basic_conf
    - basic_conf_other

- name: Enable and start qemu-guest-agent service
  service:
    name: qemu-guest-agent
    enabled: true
    state: started
  notify: 
    - Reboot the system
  tags:
    - basic_conf
    - basic_conf_other

- name: Edit /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: 127.0.1.1
    line: "127.0.1.1       {{ ansible_hostname }}.{{ local_domain }}   {{ ansible_hostname }}"
  tags:
    - basic_conf
    - basic_conf_other

- name: Edit global bash settings
  template:
    src: bash.bashrc.j2
    dest: /etc/bash.bashrc
  tags:
    - basic_conf
    - basic_conf_other