- name: Create user groups
  group:
    name: "{{ item.username }}"
  loop: "{{ users }}"
  no_log: true
  tags:
    - basic_conf
    - basic_conf_user

- name: Manage users
  user:
    name: "{{ item.0.username }}"
    password: "{{ item.0.password }}"
    state: "{{ item.0.state | default('present') }}"
    append: "{{ item.0.append | default('yes') }}"
    groups: "{{ item.0.groups | default( item.0.username ) }}"
    shell: "{{ item.0.shell | default('/bin/bash') }}"
  loop: "{{ users | subelements('hosts', 'skip_missing=True') }}"
  no_log: true
  when: item.1 == inventory_hostname or item.1 == "all"
  tags:
    - basic_conf
    - basic_conf_user

- name: Update authorized keys
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: "{{ item.0.state | default('present') }}"
  loop: "{{ vm_authorized_keys | subelements('keys', 'skip_missing=True') }}"
  no_log: true
  tags:
    - basic_conf
    - basic_conf_user

- name: Disable password authentication through SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?PasswordAuthentication
    line: "PasswordAuthentication no"
  notify:
    - Restart the OpenSSH server
  tags:
    - basic_conf
    - basic_conf_user