- name: Include variable files
  include_vars: 
    dir: ../../../global_vars
  tags:
    - pve_install

- name: Save the IP address to a variable
  environment:
    INTERFACE: "{{ pve_net_interface }}"
  shell: |
    ip -o -4 addr list $INTERFACE | awk '{print $4}' | cut -d/ -f1
  register: pve_ip
  tags:
    - pve_install

- name: Save the IP with CIDR to variable
  environment:
    INTERFACE: "{{ pve_net_interface }}"
  shell: |
    ip -4 addr show $INTERFACE | awk '/inet/ {print $2}'
  register: pve_ip_cidr
  tags:
    - pve_install

- name: Add a static IP
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "{{ pve_ip.stdout }}       {{ pve_hostname }}.{{ local_domain }}    {{ pve_hostname }}"
    state: present
  tags:
    - pve_install

- name: Remove the Debian DVD from the repository list
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom'
    state: absent
  tags:
    - pve_install

- name: Add the Proxmox repository key
  shell: |
    wget https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
  tags:
    - pve_install

- name: Add the Proxmox repository
  apt_repository:
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
    filename: pve-install-repo
  tags:
    - pve_install

- name: Update repositories and do a full system upgrade
  apt:
    update_cache: true
    name: "*"
    state: latest
    autoremove: yes
  tags:
    - pve_install

- name: Set the Postfix server configuration type to 'local only'
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "'Local only'"
    vtype: string
  tags:
    - pve_install

- name: Set the Postfix mail name
  debconf:
    name: postfix
    question: postfix/mailname
    value: "{{ pve_hostname }}.{{ local_domain }}"
    vtype: string
  tags:
    - pve_install

- name: Set mandatory packages
  set_fact:
    mandatory_packages:
      - proxmox-ve
      - postfix
      - open-iscsi
      - sudo
  tags:
    - pve_install

- name: Install PVE and other useful packages
  apt:
    update_cache: true
    name: "{{ non_mandatory_packages + mandatory_packages }}"
    state: latest
  tags:
    - pve_install

- name: Reboot the system
  reboot:
  tags:
    - pve
    - pve_install

- name: Remove the Debian 11 kernel
  shell: |
    apt remove -y linux-image-amd64 'linux-image-5.10*'
    apt remove -y os-prober
    update-grub
  tags:
    - pve_install

- name: Add the vmbr0 interface
  blockinfile:
    path: /etc/network/interfaces
    insertafter: EOF
    block: |
      auto vmbr0
      iface vmbr0 inet static
        address {{ pve_ip_cidr.stdout }}
        gateway {{ gateway }}
        bridge-ports {{ pve_net_interface }}
        bridge-stp off
        bridge-fd 0
    state: present
  tags:
    - pve_install

## REMOVE THIS PART IF YOU HAVE A VALID SUBSCRIPTION
- name: Remove the enterprise repository
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  tags:
    - pve_install

- name: Update repositories
  apt:
    update_cache: true
  tags:
    - pve_install
##

- name: Initialize the Proxmox cluster
  environment:
    NAME: "{{ pve_cluster_name }}"
  shell: pvecm create $NAME
  ignore_errors: true
  tags:
    - pve_install

- name: Reboot the system
  reboot:
  tags:
    - pve_install