---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    evictLocalStoragePods: true
    strategies:
      # Try to spread out Pod duplicates as evenly as possible
      "RemoveDuplicates":
        enabled: true
      # Automatically remove pods which violate Pod Anti Affinity
      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: true
      # Spread out Pods in order to achieve as even resource usage between Nodes as possible
      "LowNodeUtilization":
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            # If a Node's resource usage is below 'thresholds', it is considered under utilized
            thresholds:
              "cpu" : 20
              "memory": 20
            # If a Node's resource usage is above 'targetThresholds', it is considered over utilized
            targetThresholds:
              "cpu" : 50
              "memory": 50