- name: Include variable files
  include_vars: 
    dir: ../../../global_vars
  tags:
    - endpoint
    - endpoint_docker
    - endpoint_ddclient
    - endpoint_haproxy
    - endpoint_wireguard

- name: Include Docker related tasks
  include_tasks: docker.yml
  tags:
    - endpoint
    - endpoint_docker

- name: Include DDClient related tasks
  include_tasks: ddclient.yml
  tags:
    - endpoint
    - endpoint_ddclient

- name: Include HAProxy related tasks
  include_tasks: haproxy.yml
  tags:
    - endpoint
    - endpoint_haproxy

- name: Include Wireguard related tasks
  include_tasks: wireguard.yml
  tags:
    - endpoint
    - endpoint_wireguard

- name: Remove the host from the 'new_endpoint' group
  delegate_to: localhost
  lineinfile:
    path: "../inventory.ini"
    line: "{{ inventory_hostname }}"
    state: absent
  tags:
    - endpoint

- name: Add the host to the 'endpoint' group
  delegate_to: localhost
  lineinfile:
    path: "../inventory.ini"
    insertafter: "[^_]endpoint"
    line: "{{ inventory_hostname }}"
    state: present
  tags:
    - endpoint