- name: Include variable files
  include_vars:
    dir: ../../../global_vars
  tags:
    - always

- name: Include NFS installation related tasks
  include_tasks: install.yml
  tags:
    - storage
    - storage_install

- name: Include NFS permissions related tasks
  include_tasks: permissions.yml
  tags:
    - storage
    - storage_permissions