### General variables

local_user: user

timezone: City/Country

oc_domain: domain.com

local_domain: local.domain.com

# Mandatory packages to install on VMs
mandatory_packages:
  - qemu-guest-agent=1:5.2+dfsg-11+deb11u2
  - nfs-common=1:1.3.4-6

# Desired non-mandatory packages to install
non_mandatory_packages:
  - sudo=1.9.5p2-3+deb11u1
  - htop=3.0.5-7
  - vim=2:8.2.2434-3+deb11u1
  - tree=1.8.0-1+b1
  - curl=7.74.0-1.3+deb11u7
  - neofetch=7.1.0-2


### PVE variables

# Personal admin user's name
pve_user: user@pam

# Necessary 'admin' group alongside any you add yourself
pve_groups:
  - name: admin
    comment: System Administrators
    role: Administrator

# Storage to use for VM disks
vm_storage: local-lvm


### Template variables

# Template's name
template_name: debian-template

# Template's VM ID
template_id: 100

# Full URL to the disk image which will be used for the template
template_disk_image_url: https://cdimage.debian.org/cdimage/cloud/bullseye/20220816-1109/debian-11-genericcloud-amd64-20220816-1109.qcow2

# Full path and name of the disk image file once downloaded
template_disk_image_path: /root/debian-11-amd64.qcow2

# Extra space to add to the disk image when creating the template
extra_vm_disk_space: 14G


### Storage server variables

nfs_server_version: 1:1.3.4-6

# Directories to create in the NFS root share directory
share_dirs:
  - k8s
  - endpoint/wireguard_config


### Docker variables

docker_packages:
  - docker-ce=5:23.0.1-1~debian.11~bullseye
  - docker-ce-cli=5:23.0.1-1~debian.11~bullseye
  - containerd.io=1.6.16-1
  - docker-compose-plugin=2.16.0-1~debian.11~bullseye


### DDClient variables

# Docker image to use for the container
ddclient_image: linuxserver/ddclient:3.10.0


### HAProxy variables

# Docker image to use for the container
haproxy_image: haproxy:2.6.5-alpine3.16


### Wireguard variables

# Docker image to use for the container
wireguard_image: linuxserver/wireguard:1.0.20210914-alpine

# Wireguard subdomain name, used in tandem with the oc_domain variable
wireguard_subdomain: wg

# Subnet used by Wireguard peers
peer_subnet: 10.200.200.0

# DNS server used by peers
peer_dns: 192.168.100.1

# Peer identifiers separated by a comma
wireguard_peers: Admin_PC


### Kubernetes cluster variables

# Version of K3s to be installed
k3s_version: v1.25.3+k3s1

# Set to 1 to create a new cluster or 0 to keep the current one
# Automatically changed upon cluster initialization
cluster_init: 1