# This file should be encrypted using Ansible Vault
# Example values:

### User variables

# List of users, their settings as well as hosts that should have them
users:
  - username: joe
    password: 'output_of_mkpasswd'
    append: yes
    groups: [ sudo ]
    hosts:
      - 'all'
  - username: root
    password: 'output_of_mkpasswd'
    append: yes
    hosts:
      - 'all'

# List of PVE users, their settings as well as hosts that should have them
pve_users:
  - username: joe
    password: 'output_of_mkpasswd'
    append: yes
    groups: [ sudo ]
    first_name: Joe
    last_name: White
    pve_group: admin
    realm: pam
    email: mymail@mail.com
    enable: 1
    hosts:
      - 'all'

# List of authorized keys per user, which will be added to all VMs which have those users
vm_authorized_keys:
  - username: joe
    keys:
      - 'ssh-rsa bunchofgibberish user@pc'

# List of authorized keys per user, which will be added to all PVE nodes which have those users
pve_authorized_keys:
  - username: root
    keys:
      - 'ssh-rsa bunchofgibberish user@pc'
  - username: joe
    keys:
      - 'ssh-rsa bunchofgibberish user@pc'

### DNS variables

# Dynamic DNS password used for updating DNS records in Namecheap
dd_password: found_on_namecheap_domain_dashboard

### Cluster variables

# K3s token which will be used to add new nodes to the cluster
k3s_token: literally_anything
