### User variables

# List of users, their settings as well as hosts that should have them
users:
  - username: user
    password: 'your_password'
    append: yes
    groups: [ sudo ]
    hosts:
      - 'all'
  - username: root
    password: 'your_password'
    append: yes
    hosts:
      - 'all'

# List of PVE users, their settings as well as hosts that should have them
pve_users:
  - username: user
    password: 'your_password'
    append: yes
    groups: [ sudo ]
    first_name: John
    last_name: Smith
    pve_group: admin
    realm: pam
    email: JohnSmith@mail.com
    enable: 1
    hosts:
      - 'all'

# List of authorized keys per user, which will be added to all VMs which have those users
vm_authorized_keys:
  - username: user
    keys:
      - 'your_pub_key'

# List of authorized keys per user, which will be added to all PVE nodes which have those users
pve_authorized_keys:
  - username: root
    keys:
       - 'your_pub_key'
  - username: user
    keys:
        - 'your_pub_key'

### DNS variables

# Dynamic DNS password used for updating DNS records in Namecheap
dd_password: dd_password

### Cluster variables

# K3s token which will be used to add new nodes to the cluster
k3s_token: random_characters
