apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oc
  namespace: oc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: oc
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleDown:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
