apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oc
  namespace: oc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: oc
  minReplicas: 3
  maxReplicas: 6
  metrics:
    # Number of Pod replicas follow 'target' values for CPU and memory usage
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  # These policies avoid sudden jumps/drops in Pod count caused by short burts of resource usage.
  # An example would be compiling a single project, which doesn't require nor is able to use a higher number of Pods.
  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleDown:
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
