- name: Get the kubectl config
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_config_base64
  tags:
    - control_plane
    - control_plane_kubeconfig

- name: Decode the config and store it in a variable
  set_fact:
    k3s_config: "{{ k3s_config_base64['content'] | b64decode }}"
  tags:
    - control_plane
    - control_plane_kubeconfig

- name: Create the kube directory
  file:
    path: "/home/{{ local_user }}/.kube"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: 0700
  delegate_to: localhost
  tags:
    - control_plane
    - control_plane_kubeconfig
  
- name: Write the kubectl config
  copy:
    content: "{{ k3s_config }}"
    dest: "/home/{{ local_user }}/.kube/config"
    mode: 0600
  delegate_to: localhost
  tags:
    - control_plane
    - control_plane_kubeconfig

- name: Change the kubectl endpoint address
  lineinfile:
    path: "/home/{{ local_user }}/.kube/config"
    regex: "server: https://"
    line: "    server: https://{{ groups['endpoint'].0 | default(new_endpoint_ip) }}:6443"
  delegate_to: localhost
  become: false
  tags:
    - control_plane
    - control_plane_kubeconfig