# This playbook requires the "host_group", "host_ip" and "host_state" variables defined with the --extra-vars flag

- name: Manage the Ansible inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Edit the inventory
      lineinfile:
        path: ../inventory.ini
        insertafter: "{{ host_group }}"
        line: "{{ host_ip }}"
        state: "{{ host_state }}"