# This playbook installs and configures PVE on a base Debian installation.
# Available tags:
#  - pve_install
#  - pve_config
#  - pve_config_general
#  - pve_config_users

- name: Install PVE
  hosts: pve
  remote_user: root
  gather_facts: false
  roles:
    - ../roles/pve_install
  tags:
    - pve
    - pve-install

- name: Configure PVE settings and users
  hosts: pve
  remote_user: root
  gather_facts: false
  roles:
    - ../roles/pve_config
  tags:
    - pve
    - pve-config
    - pve-users