# This playbook should be run once PVE has been fully configured and a VM template has been created. 
# It uses groups specified in inventory.ini to configure specified hosts and create a fully functional Kubernetes cluster from scratch alongside a VPN, external load balancer and centralized storage server.
# List of tags:
#  - always
#  - basic_conf
#  - basic_conf_user
#  - basic_conf_other
#  - storage
#  - storage_install
#  - storage_permissions
#  - endpoint
#  - endpoint_docker
#  - endpoint_ddclient
#  - endpoint_haproxy
#  - endpoint_wireguard
#  - control_plane
#  - control_plane_cleanup
#  - control_plane_install
#  - control_plane_kubeconfig
#  - node
#  - node_cleanup
#  - node_install

- name: Gather facts
  hosts: all
  remote_user: root
  gather_facts: true
  tags:
    - always

- name: Manage general configs
  hosts: all, !pve
  remote_user: root
  gather_facts: false
  roles:
    - ../roles/basic_conf
  tags:
    - basic_conf

- name: Configure the storage server
  hosts: new_storage,storage
  remote_user: root
  gather_facts: false
  roles:
    - ../roles/storage
  tags:
    - storage

- name: Configure the endpoint
  hosts: new_endpoint, endpoint
  remote_user: root
  gather_facts: false
  roles:
    - ../roles/endpoint
  tags:
    - endpoint

- name: Configure control planes
  hosts: new_control_plane, control_plane
  remote_user: root
  serial: 1
  gather_facts: false
  roles:
    - ../roles/control_plane
  tags:
    - control_plane

- name: Configure nodes
  hosts: new_zone_a_node, zone_a_node, new_zone_b_node, zone_b_node
  remote_user: root
  serial: 1
  gather_facts: false
  roles:
    - ../roles/node
  tags:
    - node