---
# Source: mysql-innodbcluster/templates/service_account_cluster.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: oc
---
# Source: mysql-innodbcluster/templates/cluster_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-secret
  namespace: oc
stringData:
  rootUser: "root"
  rootHost: "%"
data:
  rootPassword: "emF2cnNuaQ=="
---
# Source: mysql-innodbcluster/templates/deployment_cluster.yaml
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql
  namespace: oc
spec:
  instances: 3
  tlsUseSelfSigned: true
  router:
    instances: 3
    version: 8.0.31
    podSpec:
      name: mysql-router
      resources:
        requests:
          cpu: 30m
          memory: 30Mi
        limits:
          cpu: 90m
          memory: 90Mi
  secretName: mysql-cluster-secret
  imagePullPolicy : IfNotPresent
  baseServerId: 1000
  version: 8.0.31
  serviceAccountName: mysql-sa
  datadirVolumeClaimTemplate:
    storageClassName: nfs-subdir-provisioner
    accessModes: [ "ReadWriteMany" ]
    resources:
      requests:
        storage: "5Gi"  
  podSpec: 
    podLabels: 
      name: mysql
    containers:
    - name: mysql
      resources:
        requests:
          cpu: 200m
          memory: 700Mi
        limits:
          cpu: 1000m
          memory: 1400Mi
