- name: Remove the Proxmox enterprise repository
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  tags:
    - pve_config
    - pve_config_general

- name: Add the Proxmox no-subscription repository
  apt_repository:
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription"
    filename: pve-no-subscription
  tags:
    - pve_config
    - pve_config_general

- name: Update repositories and install useful packages
  apt:
    update_cache: true
    name: "{{ non_mandatory_packages }}"
    state: latest
  tags:
    - pve_config
    - pve_config_general

- name: Edit global bash settings
  template:
    src: bash.bashrc.j2
    dest: /etc/bash.bashrc
  tags:
    - pve_config
    - pve_config_general

- name: Create the firewall directory
  file:
    path: /etc/pve/firewall
    state: directory
  tags:
    - pve_config
    - pve_config_general

- name: Add security groups to a temporary file
  template:
    src: cluster.fw.j2
    dest: /tmp/cluster.fw
  tags:
    - pve_config
    - pve_config_general

- name: Add security groups to the cluster config
  shell: mv /tmp/cluster.fw /etc/pve/firewall/
  tags:
    - pve_config
    - pve_config_general