- name: Include variable files
  include_vars:
    dir: ../../../global_vars
  tags:
    - always

- name: Include PVE general config related tasks
  include_tasks: general.yml
  tags:
    - pve_config
    - pve_config_general

- name: Include user config related tasks
  include_tasks: user.yml
  tags:
    - pve_config
    - pve_config_users