- name: Create Proxmox groups and define their permissions
  environment:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    role: "{{ item.role }}"
  shell: |
    pveum group add $name -comment "$comment"
    pveum acl modify / -group $name -role $role
  loop: "{{ pve_groups }}"
  no_log: true
  tags:
    - pve_config
    - pve_config_users

- name: Create user groups
  group:
    name: "{{ item.username }}"
  loop: "{{ users }}"
  no_log: true
  tags:
    - pve_config
    - pve_config_users

- name: Manage users
  user:
    name: "{{ item.0.username }}"
    password: "{{ item.0.password }}"
    state: "{{ item.0.state | default('present') }}"
    append: "{{ item.0.append | default('yes') }}"
    groups: "{{ item.0.groups | default( item.0.username ) }}"
    shell: "{{ item.0.shell | default('/bin/bash') }}"
  loop: "{{ users | subelements('hosts', 'skip_missing=True') }}"
  no_log: true
  when: item.1 == inventory_hostname or item.1 == "all"
  tags:
    - pve_config
    - pve_config_users

- name: Add users to Proxmox's realms
  environment:
    name: "{{ item.0.username }}"
    first_name: "{{ item.0.first_name }}"
    last_name: "{{ item.0.last_name }}"
    group: "{{ item.0.pve_group }}"
    realm: "{{ item.0.realm }}"
    enable: "{{ item.0.enable }}"
    append: "{{ item.0.append }}"
    email: "{{ item.0.email }}"
  shell: |
    pveum useradd ${name}@${realm}
    pveum user modify ${name}@${realm} \
      --firstname "${first_name}" \
      --lastname "${last_name}" \
      --append ${append} \
      --groups "${group}" \
      --email ${email} \
      --enable ${enable}
  loop: "{{ pve_users | subelements('hosts', 'skip_missing=True') }}"
  no_log: true
  when: item.1 == inventory_hostname or item.1 == "all"
  tags:
    - pve_config
    - pve_config_users

- name: Update authorized keys
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: "{{ item.0.state | default('present') }}"
  loop: "{{ pve_authorized_keys | subelements('keys', 'skip_missing=True') }}"
  no_log: true
  tags:
    - pve_config
    - pve_config_users

- name: Disable PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?PasswordAuthentication
    line: PasswordAuthentication no
  notify:
    - Restart the OpenSSH server
  tags:
    - pve_config
    - pve_config_users